# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWeibo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftWeibo

end

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'SnapKit'
